name: Build and Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Numéro de version de l''application'
        required: true
        default: '1.0.0' # Vous pouvez définir une valeur par défaut ici

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  VersionUp:
    runs-on: macos-latest
    outputs:
      new_version: ${{ steps.set_version.outputs.new_version }}
      new_build_number: ${{ steps.set_version.outputs.new_build_number }}
    steps:
      - uses: actions/checkout@v4
      - name: Set Version and Build Number
        id: set_version
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ github.event.inputs.version }}
          build-number: ${{github.run_number}}

  Commit_Push_and_Tag:
    needs: [SwiftLint, VersionUp]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit and Push Changes
        run: |
          git config --global user.email "bryan.battu@gmail.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Bump version to ${{needs.VersionUp.outputs.new_version}} and build number to ${{needs.VersionUp.outputs.new_build_number}}"
          git push

      - name: Tag the release
        run: |
          git tag -a v${{needs.VersionUp.outputs.new_version}} -m "Release version ${{needs.VersionUp.outputs.new_version}}"
          git push --tags

  Build:
    needs: Commit_Push_and_Tag
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pod install --repo-update
        shell: bash

      - name: Clean
        run: |
          xcodebuild clean -workspace MuscleUp.xcworkspace -scheme MuscleUp

      - name: Build
        run: |
          xcodebuild build -workspace MuscleUp.xcworkspace -scheme MuscleUp -sdk iphoneos CODE_SIGNING_ALLOWED=No

      - name: Run tests
        run: |
          xcodebuild test -workspace MuscleUp.xcworkspace -scheme MuscleUp -sdk iphoneos -destination "platform=iOS Simulator,name=iPhone 15 Pro Max" CODE_SIGNING_ALLOWED=No
